language: node_js
node_js:
  - 9
script:
  -
deploy:
  provider: firebase
  token:
    secure: "SCwquylt9yNJCoWb30ANRCaTIsKeYyCrc8QOf4P0qXQfKWBQJNSYM9ialyE+bfUeMDtSw/xnPpfnAdGuXfW2t3dtbkT34hlHzu0EeNa7xbaSQ6mNMUgHlxTkVM8xt4/v4eh0VkfcGJTAWpo/vD8M6QXjoilcBbo9G98hl8P2cwpx3oTzu1Jfu1xDVuM6bf80GWHd6yTDV3DbWqzIhE4ZAdllDc3L48MusAowXWsrQ2zjc2oQ7PAfaP+g9wpcsWvoHdCNTh56ZkhfyaVxxFZlMafCYHDY1BtqSFLHt2OFsvjGP3YY3eDXQlCAleVLxINJFCKnOyTBUj0811VlqRO8GjWwlUYx8z3Csz8dlchud+pwxDj2ENgrHa31vWf077G0vjnIlAnzn8+0vV8cPsyQcIzbYUkX+GX/cYtGNi6tRtc6p/bhUPkgbH5dcFyE5z0qZf1JfVK5j4HijWdbskhjvKe8HJoCCINuc1ri1GGrRCieS2g+oan4/SBy7Th+vJJyGxUqB/F/Y7DuBUdkDAt4aa92gS+Bff9tncNFBRlXzfLAfCNg9S8GVwKXNZIbUq2WbbVlGFwRWsD/fyyTWoO6F2Er38g9eltWLlFVBBfNUWTWOo3WvygBqIA4vpwVpExpFfO7bWmpDzO2Js1Yv5tbLjD2N5DKpgKQL3gd651u4AI="