language: node_js
node_js:
- 9
script:
- 
deploy:
  provider: firebase
  token:
    secure: DgbNFC2PT3UHt6vshqgUxP5W++G35GEaNKhgxS/d1ZELgnX2xpVjRl37/q1aVsBW7xkUQqCDZsyEJNFyOaR0ztpCf9zKd7Icw3zF6lk3cYD/Pzb2GF3XB5DB9dzL2MXcLvjHj7o3lmCXSXO7mZ25jHINTbVbhdyjY+RAuYDU7YV5G8zuUEA0MIMbvi4Ra/5FnlEd5jQb9m0ZgLy0hp2YSHxdwQDW5uWqKOZgipRcpftCRnUtoGZYxn3CLysryepTX1x/VfvbFVkZa93uGIL3FwKL0hQ9srl2iSpUJ5SoAybEy8jJ7uk5WldNX4HjkDQik5t1St84UjWffuQXNSVUkV/t5p1OD/B2loycwq6lncjqOuCSaUWWiCDImixLdGkBgnu6rzqxTcY7rnVKkO6xt2QoOz7vZByPRYQOwOMLiNDLRjUSn1Xg3YhLcTnWl5sUw201Pb5Ii3hTmrnsZJztTWD+4dF2D9I7oHmTL0CfdY/OCti32eWwmgJTM6WWQMQt3bA3X/PdFtOUyHxDLyPFwWatzv5PP15yNBr2iKbOKrI+n4vLqHtX2J9/JiRB7FYXFsufqo8TY3r+TPa6qoubN6i7EFepQtb1ecu9rKKBH7Zzm/y4AUp8nK8Bu7dEeFnoTSKBh+aXcEsHYNnnulPwuLRDFxn3WQ9+KLjQDIu/F1M=
